// <auto-generated />
namespace Gucci.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class event_edit03 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(event_edit03));
        
        string IMigrationMetadata.Id
        {
            get { return "201904292035171_event_edit03"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
