namespace DataAccessLayer.Migrations
{
    using System.Data.Entity.Migrations;
    
    public partial class idsToInts : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.UserAction", "UserId", "dbo.User");
            DropForeignKey("dbo.UserAction", "Action", "dbo.Action");
            DropForeignKey("dbo.Attendee", "EventId", "dbo.Event");
            DropForeignKey("dbo.EventRole", "EventId", "dbo.Event");
            DropForeignKey("dbo.EventTag", "EventId", "dbo.Event");
            DropForeignKey("dbo.Event", "UserId", "dbo.User");
            DropForeignKey("dbo.Attendee", "UserId", "dbo.User");
            DropForeignKey("dbo.Blocklist", "UserId1", "dbo.User");
            DropForeignKey("dbo.Blocklist", "UserId2", "dbo.User");
            DropForeignKey("dbo.Friend", "UserId1", "dbo.User");
            DropForeignKey("dbo.Friend", "UserId2", "dbo.User");
            DropForeignKey("dbo.UserClaim", "UId", "dbo.User");
            DropForeignKey("dbo.UserRating", "RatedId1", "dbo.User");
            DropForeignKey("dbo.UserRating", "RaterId1", "dbo.User");
            DropForeignKey("dbo.UserTag", "UserId", "dbo.User");
            DropForeignKey("dbo.EventTag", "TagId", "dbo.Tag");
            DropForeignKey("dbo.UserTag", "TagId", "dbo.Tag");
            DropIndex("dbo.Attendee", new[] { "EventId" });
            DropIndex("dbo.Attendee", new[] { "UserId" });
            DropIndex("dbo.Event", new[] { "UserId" });
            DropIndex("dbo.Blocklist", new[] { "UserId1" });
            DropIndex("dbo.Blocklist", new[] { "UserId2" });
            DropIndex("dbo.EventRole", new[] { "EventId" });
            DropIndex("dbo.EventTag", new[] { "EventId" });
            DropIndex("dbo.EventTag", new[] { "TagId" });
            DropIndex("dbo.Friend", new[] { "UserId1" });
            DropIndex("dbo.Friend", new[] { "UserId2" });
            DropIndex("dbo.UserAction", new[] { "Action" });
            DropIndex("dbo.UserAction", new[] { "UserId" });
            DropIndex("dbo.UserClaim", new[] { "UId" });
            DropIndex("dbo.UserRating", new[] { "RaterId1" });
            DropIndex("dbo.UserRating", new[] { "RatedId1" });
            DropIndex("dbo.UserTag", new[] { "TagId" });
            DropIndex("dbo.UserTag", new[] { "UserId" });
            RenameColumn(table: "dbo.UserAction", name: "Action", newName: "ActionId");
            DropPrimaryKey("dbo.Action");
            DropPrimaryKey("dbo.Attendee");
            DropPrimaryKey("dbo.Event");
            DropPrimaryKey("dbo.User");
            DropPrimaryKey("dbo.EventRole");
            DropPrimaryKey("dbo.EventTag");
            DropPrimaryKey("dbo.Tag");
            DropPrimaryKey("dbo.UserAction");
            DropPrimaryKey("dbo.UserClaim");
            DropPrimaryKey("dbo.UserRating");
            DropPrimaryKey("dbo.UserTag");
            AlterColumn("dbo.Action", "ActionId", c => c.Int(nullable: false, identity: false));
            AlterColumn("dbo.Attendee", "EventId", c => c.Int(nullable: false));
            AlterColumn("dbo.Attendee", "UserId", c => c.Int(nullable: false));
            AlterColumn("dbo.Event", "EventId", c => c.Int(nullable: false, identity: false));
            AlterColumn("dbo.Event", "UserId", c => c.Int(nullable: false));
            AlterColumn("dbo.User", "UserId", c => c.Int(nullable: false, identity: false));
            AlterColumn("dbo.Blocklist", "UserId1", c => c.Int(nullable: false));
            AlterColumn("dbo.Blocklist", "UserId2", c => c.Int(nullable: false));
            AlterColumn("dbo.EventRole", "EventId", c => c.Int(nullable: false));
            AlterColumn("dbo.EventTag", "EventId", c => c.Int(nullable: false));
            AlterColumn("dbo.EventTag", "TagId", c => c.Int(nullable: false));
            AlterColumn("dbo.Tag", "TagId", c => c.Int(nullable: false, identity: false));
            AlterColumn("dbo.Friend", "UserId1", c => c.Int(nullable: false));
            AlterColumn("dbo.Friend", "UserId2", c => c.Int(nullable: false));
            AlterColumn("dbo.UserAction", "SessionId", c => c.Int(nullable: false));
            AlterColumn("dbo.UserAction", "ActionId", c => c.Int(nullable: false));
            AlterColumn("dbo.UserAction", "UserId", c => c.Int(nullable: false));
            AlterColumn("dbo.UserClaim", "UId", c => c.Int(nullable: false));
            AlterColumn("dbo.UserRating", "RaterId1", c => c.Int(nullable: false));
            AlterColumn("dbo.UserRating", "RatedId1", c => c.Int(nullable: false));
            AlterColumn("dbo.UserTag", "TagId", c => c.Int(nullable: false));
            AlterColumn("dbo.UserTag", "UserId", c => c.Int(nullable: false));
            AddPrimaryKey("dbo.Action", "ActionId");
            AddPrimaryKey("dbo.Attendee", new[] { "EventId", "UserId" });
            AddPrimaryKey("dbo.Event", "EventId");
            AddPrimaryKey("dbo.User", "UserId");
            AddPrimaryKey("dbo.EventRole", new[] { "EventId", "RoleName" });
            AddPrimaryKey("dbo.EventTag", new[] { "EventId", "TagId" });
            AddPrimaryKey("dbo.Tag", "TagId");
            AddPrimaryKey("dbo.UserAction", new[] { "ActionTime", "SessionId", "ActionId" });
            AddPrimaryKey("dbo.UserClaim", new[] { "UId", "ClaimId" });
            AddPrimaryKey("dbo.UserRating", new[] { "RaterId1", "RatedId1" });
            AddPrimaryKey("dbo.UserTag", new[] { "TagId", "UserId" });
            CreateIndex("dbo.Attendee", "EventId");
            CreateIndex("dbo.Attendee", "UserId");
            CreateIndex("dbo.Event", "UserId");
            CreateIndex("dbo.Blocklist", "UserId1");
            CreateIndex("dbo.Blocklist", "UserId2");
            CreateIndex("dbo.EventRole", "EventId");
            CreateIndex("dbo.EventTag", "EventId");
            CreateIndex("dbo.EventTag", "TagId");
            CreateIndex("dbo.Friend", "UserId1");
            CreateIndex("dbo.Friend", "UserId2");
            CreateIndex("dbo.UserAction", "ActionId");
            CreateIndex("dbo.UserAction", "UserId");
            CreateIndex("dbo.UserClaim", "UId");
            CreateIndex("dbo.UserRating", "RaterId1");
            CreateIndex("dbo.UserRating", "RatedId1");
            CreateIndex("dbo.UserTag", "TagId");
            CreateIndex("dbo.UserTag", "UserId");
            AddForeignKey("dbo.UserAction", "UserId", "dbo.User", "UserId", cascadeDelete: true);
            AddForeignKey("dbo.UserAction", "ActionId", "dbo.Action", "ActionId", cascadeDelete: true);
            AddForeignKey("dbo.Attendee", "EventId", "dbo.Event", "EventId", cascadeDelete: false);
            AddForeignKey("dbo.EventRole", "EventId", "dbo.Event", "EventId", cascadeDelete: true);
            AddForeignKey("dbo.EventTag", "EventId", "dbo.Event", "EventId", cascadeDelete: true);
            AddForeignKey("dbo.Event", "UserId", "dbo.User", "UserId", cascadeDelete: true);
            AddForeignKey("dbo.Attendee", "UserId", "dbo.User", "UserId", cascadeDelete: true);
            AddForeignKey("dbo.Blocklist", "UserId1", "dbo.User", "UserId", cascadeDelete: true);
            AddForeignKey("dbo.Blocklist", "UserId2", "dbo.User", "UserId", cascadeDelete: false);
            AddForeignKey("dbo.Friend", "UserId1", "dbo.User", "UserId", cascadeDelete: true);
            AddForeignKey("dbo.Friend", "UserId2", "dbo.User", "UserId", cascadeDelete: false);
            AddForeignKey("dbo.UserClaim", "UId", "dbo.User", "UserId", cascadeDelete: true);
            AddForeignKey("dbo.UserRating", "RatedId1", "dbo.User", "UserId", cascadeDelete: false);
            AddForeignKey("dbo.UserRating", "RaterId1", "dbo.User", "UserId", cascadeDelete: true);
            AddForeignKey("dbo.UserTag", "UserId", "dbo.User", "UserId", cascadeDelete: true);
            AddForeignKey("dbo.EventTag", "TagId", "dbo.Tag", "TagId", cascadeDelete: true);
            AddForeignKey("dbo.UserTag", "TagId", "dbo.Tag", "TagId", cascadeDelete: true);
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.UserTag", "TagId", "dbo.Tag");
            DropForeignKey("dbo.EventTag", "TagId", "dbo.Tag");
            DropForeignKey("dbo.UserTag", "UserId", "dbo.User");
            DropForeignKey("dbo.UserRating", "RaterId1", "dbo.User");
            DropForeignKey("dbo.UserRating", "RatedId1", "dbo.User");
            DropForeignKey("dbo.UserClaim", "UId", "dbo.User");
            DropForeignKey("dbo.Friend", "UserId2", "dbo.User");
            DropForeignKey("dbo.Friend", "UserId1", "dbo.User");
            DropForeignKey("dbo.Blocklist", "UserId2", "dbo.User");
            DropForeignKey("dbo.Blocklist", "UserId1", "dbo.User");
            DropForeignKey("dbo.Attendee", "UserId", "dbo.User");
            DropForeignKey("dbo.Event", "UserId", "dbo.User");
            DropForeignKey("dbo.EventTag", "EventId", "dbo.Event");
            DropForeignKey("dbo.EventRole", "EventId", "dbo.Event");
            DropForeignKey("dbo.Attendee", "EventId", "dbo.Event");
            DropForeignKey("dbo.UserAction", "ActionId", "dbo.Action");
            DropForeignKey("dbo.UserAction", "UserId", "dbo.User");
            DropIndex("dbo.UserTag", new[] { "UserId" });
            DropIndex("dbo.UserTag", new[] { "TagId" });
            DropIndex("dbo.UserRating", new[] { "RatedId1" });
            DropIndex("dbo.UserRating", new[] { "RaterId1" });
            DropIndex("dbo.UserClaim", new[] { "UId" });
            DropIndex("dbo.UserAction", new[] { "UserId" });
            DropIndex("dbo.UserAction", new[] { "ActionId" });
            DropIndex("dbo.Friend", new[] { "UserId2" });
            DropIndex("dbo.Friend", new[] { "UserId1" });
            DropIndex("dbo.EventTag", new[] { "TagId" });
            DropIndex("dbo.EventTag", new[] { "EventId" });
            DropIndex("dbo.EventRole", new[] { "EventId" });
            DropIndex("dbo.Blocklist", new[] { "UserId2" });
            DropIndex("dbo.Blocklist", new[] { "UserId1" });
            DropIndex("dbo.Event", new[] { "UserId" });
            DropIndex("dbo.Attendee", new[] { "UserId" });
            DropIndex("dbo.Attendee", new[] { "EventId" });
            DropPrimaryKey("dbo.UserTag");
            DropPrimaryKey("dbo.UserRating");
            DropPrimaryKey("dbo.UserClaim");
            DropPrimaryKey("dbo.UserAction");
            DropPrimaryKey("dbo.Tag");
            DropPrimaryKey("dbo.EventTag");
            DropPrimaryKey("dbo.EventRole");
            DropPrimaryKey("dbo.User");
            DropPrimaryKey("dbo.Event");
            DropPrimaryKey("dbo.Attendee");
            DropPrimaryKey("dbo.Action");
            AlterColumn("dbo.UserTag", "UserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.UserTag", "TagId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.UserRating", "RatedId1", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.UserRating", "RaterId1", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.UserClaim", "UId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.UserAction", "UserId", c => c.String(maxLength: 128));
            AlterColumn("dbo.UserAction", "ActionId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.UserAction", "SessionId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Friend", "UserId2", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Friend", "UserId1", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Tag", "TagId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.EventTag", "TagId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.EventTag", "EventId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.EventRole", "EventId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Blocklist", "UserId2", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Blocklist", "UserId1", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.User", "UserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Event", "UserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Event", "EventId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Attendee", "UserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Attendee", "EventId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Action", "ActionId", c => c.String(nullable: false, maxLength: 128));
            AddPrimaryKey("dbo.UserTag", new[] { "TagId", "UserId" });
            AddPrimaryKey("dbo.UserRating", new[] { "RaterId1", "RatedId1" });
            AddPrimaryKey("dbo.UserClaim", new[] { "UId", "ClaimId" });
            AddPrimaryKey("dbo.UserAction", new[] { "ActionTime", "SessionId", "Action" });
            AddPrimaryKey("dbo.Tag", "TagId");
            AddPrimaryKey("dbo.EventTag", new[] { "EventId", "TagId" });
            AddPrimaryKey("dbo.EventRole", new[] { "EventId", "RoleName" });
            AddPrimaryKey("dbo.User", "UserId");
            AddPrimaryKey("dbo.Event", "EventId");
            AddPrimaryKey("dbo.Attendee", new[] { "EventId", "UserId" });
            AddPrimaryKey("dbo.Action", "ActionId");
            RenameColumn(table: "dbo.UserAction", name: "ActionId", newName: "Action");
            CreateIndex("dbo.UserTag", "UserId");
            CreateIndex("dbo.UserTag", "TagId");
            CreateIndex("dbo.UserRating", "RatedId1");
            CreateIndex("dbo.UserRating", "RaterId1");
            CreateIndex("dbo.UserClaim", "UId");
            CreateIndex("dbo.UserAction", "UserId");
            CreateIndex("dbo.UserAction", "Action");
            CreateIndex("dbo.Friend", "UserId2");
            CreateIndex("dbo.Friend", "UserId1");
            CreateIndex("dbo.EventTag", "TagId");
            CreateIndex("dbo.EventTag", "EventId");
            CreateIndex("dbo.EventRole", "EventId");
            CreateIndex("dbo.Blocklist", "UserId2");
            CreateIndex("dbo.Blocklist", "UserId1");
            CreateIndex("dbo.Event", "UserId");
            CreateIndex("dbo.Attendee", "UserId");
            CreateIndex("dbo.Attendee", "EventId");
            AddForeignKey("dbo.UserTag", "TagId", "dbo.Tag", "TagId", cascadeDelete: true);
            AddForeignKey("dbo.EventTag", "TagId", "dbo.Tag", "TagId", cascadeDelete: true);
            AddForeignKey("dbo.UserTag", "UserId", "dbo.User", "UserId", cascadeDelete: true);
            AddForeignKey("dbo.UserRating", "RaterId1", "dbo.User", "UserId", cascadeDelete: true);
            AddForeignKey("dbo.UserRating", "RatedId1", "dbo.User", "UserId", cascadeDelete: false);
            AddForeignKey("dbo.UserClaim", "UId", "dbo.User", "UserId", cascadeDelete: true);
            AddForeignKey("dbo.Friend", "UserId2", "dbo.User", "UserId", cascadeDelete: false);
            AddForeignKey("dbo.Friend", "UserId1", "dbo.User", "UserId", cascadeDelete: true);
            AddForeignKey("dbo.Blocklist", "UserId2", "dbo.User", "UserId", cascadeDelete: false);
            AddForeignKey("dbo.Blocklist", "UserId1", "dbo.User", "UserId", cascadeDelete: true);
            AddForeignKey("dbo.Attendee", "UserId", "dbo.User", "UserId", cascadeDelete: true);
            AddForeignKey("dbo.Event", "UserId", "dbo.User", "UserId", cascadeDelete: true);
            AddForeignKey("dbo.EventTag", "EventId", "dbo.Event", "EventId", cascadeDelete: true);
            AddForeignKey("dbo.EventRole", "EventId", "dbo.Event", "EventId", cascadeDelete: true);
            AddForeignKey("dbo.Attendee", "EventId", "dbo.Event", "EventId", cascadeDelete: false);
            AddForeignKey("dbo.UserAction", "Action", "dbo.Action", "ActionId", cascadeDelete: true);
            AddForeignKey("dbo.UserAction", "UserId", "dbo.User", "UserId");
        }
    }
}
